### ISSUE TITLE
Problem with ISTAC plugin in QGIS:

### ISSUE THREAD

**Issue by PilarIbarrondo** [eDatos/istacqgis#4]
I don't know why the ISTAC plugin for QGIS doesn't work. I get the following error message:

TypeError: string indices must be integers, not 'str' 
Traceback (most recent call last):
  File "C:\Users/Pilar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\istacqgis\BaseDialog.py", line 95, in getCbSubjects
    self.setCbIndicators(subject)
  File "C:\Users/Pilar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\istacqgis\BaseDialog.py", line 107, in setCbIndicators
    indicators_title_es = {indicator["id"]: indicator["title"]["es"] for indicator in indicators['items']}
                                                                                      ~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by rafsuaveg** [comment]
I also have the same error. Has anyone solved it?
